KidscotchWebApp/Controllers/ClothCompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KidscotchWebApp.Data;
using KidscotchWebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace KidscotchWebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class ClothCompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClothCompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ClothCompanies
        public async Task<IActionResult> Index()
        {
            return View(await _context.ClothCompanies.ToListAsync());
        }

        // GET: ClothCompanies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clothCompany = await _context.ClothCompanies
                .FirstOrDefaultAsync(m => m.ClothCompanyID == id);
            if (clothCompany == null)
            {
                return NotFound();
            }

            return View(clothCompany);
        }

        // GET: ClothCompanies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ClothCompanies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClothCompanyID,ClothCompanyName,About")] ClothCompany clothCompany)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clothCompany);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clothCompany);
        }

        // GET: ClothCompanies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clothCompany = await _context.ClothCompanies.FindAsync(id);
            if (clothCompany == null)
            {
                return NotFound();
            }
            return View(clothCompany);
        }

        // POST: ClothCompanies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClothCompanyID,ClothCompanyName,About")] ClothCompany clothCompany)
        {
            if (id != clothCompany.ClothCompanyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clothCompany);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClothCompanyExists(clothCompany.ClothCompanyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clothCompany);
        }

        // GET: ClothCompanies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clothCompany = await _context.ClothCompanies
                .FirstOrDefaultAsync(m => m.ClothCompanyID == id);
            if (clothCompany == null)
            {
                return NotFound();
            }

            return View(clothCompany);
        }

        // POST: ClothCompanies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clothCompany = await _context.ClothCompanies.FindAsync(id);
            _context.ClothCompanies.Remove(clothCompany);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClothCompanyExists(int id)
        {
            return _context.ClothCompanies.Any(e => e.ClothCompanyID == id);
        }
    }
}

KidscotchWebApp/Controllers/ClothInfoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KidscotchWebApp.Data;
using KidscotchWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace KidscotchWebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class ClothInfoesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public ClothInfoesController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _environment = env;
        }

        // GET: ClothInfoes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ClothInfos.Include(c => c.ClothCompany).Include(c => c.ShopCategory);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ClothInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clothInfo = await _context.ClothInfos
                .Include(c => c.ClothCompany)
                .Include(c => c.ShopCategory)
                .FirstOrDefaultAsync(m => m.ClothInfoID == id);
            if (clothInfo == null)
            {
                return NotFound();
            }

            return View(clothInfo);
        }

        // GET: ClothInfoes/Create
        public IActionResult Create()
        {
            ViewData["ClothCompanyID"] = new SelectList(_context.ClothCompanies, "ClothCompanyID", "ClothCompanyName");
            ViewData["ShopCategoryID"] = new SelectList(_context.ShopCategories, "ShopCategoryID", "ShopCategoryName");
            return View();
        }

        // POST: ClothInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClothInfoID,Name,ClothPrice,SizeChart,Feature,ShopCategoryID,ClothCompanyID,File")] ClothInfo clothInfo)
        {
            using (var memoryStream = new MemoryStream())
            {
                await clothInfo.File.FormFile.CopyToAsync(memoryStream);

                string photoname = clothInfo.File.FormFile.FileName;
                clothInfo.Extension = Path.GetExtension(photoname);
                if (!".jpg.jpeg.png.gif.bmp".Contains(clothInfo.Extension.ToLower()))
                {
                    ModelState.AddModelError("File.FormFile", "Only Images Allowed");
                }
                else
                {
                    ModelState.Remove("Extension");
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(clothInfo);
                await _context.SaveChangesAsync();
                var rootFolder = Path.Combine(_environment.WebRootPath, "cloths");
                if (!Directory.Exists(rootFolder))
                {
                    Directory.CreateDirectory(rootFolder);
                }
                string filename = clothInfo.ClothInfoID + clothInfo.Extension;
                var filePath = Path.Combine(rootFolder, filename);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await clothInfo.File.FormFile.CopyToAsync(fileStream).ConfigureAwait(false);
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClothCompanyID"] = new SelectList(_context.ClothCompanies, "ClothCompanyID", "ClothCompanyName", clothInfo.ClothCompanyID);
            ViewData["ShopCategoryID"] = new SelectList(_context.ShopCategories, "ShopCategoryID", "ShopCategoryName", clothInfo.ShopCategoryID);
            return View(clothInfo);
        }

        // GET: ClothInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clothInfo = await _context.ClothInfos.FindAsync(id);
            if (clothInfo == null)
            {
                return NotFound();
            }
            ViewData["ClothCompanyID"] = new SelectList(_context.ClothCompanies, "ClothCompanyID", "ClothCompanyName", clothInfo.ClothCompanyID);
            ViewData["ShopCategoryID"] = new SelectList(_context.ShopCategories, "ShopCategoryID", "ShopCategoryName", clothInfo.ShopCategoryID);
            return View(clothInfo);
        }

        // POST: ClothInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClothInfoID,Name,ClothPrice,SizeChart,Feature,ShopCategoryID,ClothCompanyID,Extension")] ClothInfo clothInfo)
        {
            if (id != clothInfo.ClothInfoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clothInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClothInfoExists(clothInfo.ClothInfoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClothCompanyID"] = new SelectList(_context.ClothCompanies, "ClothCompanyID", "ClothCompanyName", clothInfo.ClothCompanyID);
            ViewData["ShopCategoryID"] = new SelectList(_context.ShopCategories, "ShopCategoryID", "ShopCategoryName", clothInfo.ShopCategoryID);
            return View(clothInfo);
        }

        // GET: ClothInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clothInfo = await _context.ClothInfos
                .Include(c => c.ClothCompany)
                .Include(c => c.ShopCategory)
                .FirstOrDefaultAsync(m => m.ClothInfoID == id);
            if (clothInfo == null)
            {
                return NotFound();
            }

            return View(clothInfo);
        }

        // POST: ClothInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clothInfo = await _context.ClothInfos.FindAsync(id);
            _context.ClothInfos.Remove(clothInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClothInfoExists(int id)
        {
            return _context.ClothInfos.Any(e => e.ClothInfoID == id);
        }
    }
}

KidscotchWebApp/Controllers/OrderController.cs
using KidscotchWebApp.Data;
using KidscotchWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KidscotchWebApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.CartInfos.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.CartInfos
                .Include(m => m.CartCartItems)
                .Where(m => m.CartID == id).FirstOrDefaultAsync();
            if (cart != null)
            {
                int quantity = 0;
                float total = 0.0F;
                foreach (CartItem item in cart.CartCartItems)
                {
                    item.ClothInfo = await _context.ClothInfos.Where(m => m.ClothInfoID == item.ClothInfoID).FirstOrDefaultAsync();
                    quantity += item.Quantity;
                    total += item.Total;
                }
                ViewData["Total"] = total;
                ViewData["Quantity"] = quantity;
            }
            return View(cart);
        }
    }
}

KidscotchWebApp/ViewComponents/CompanyMenuViewComponent.cs
using KidscotchWebApp.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KidscotchWebApp.ViewComponents
{
    public class CompanyMenuViewComponent : ViewComponent
    {
		private readonly ICompanyMenuAccessService _menuAccessService;

		public CompanyMenuViewComponent(ICompanyMenuAccessService menuAccessService)
		{
			_menuAccessService = menuAccessService;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var items = await _menuAccessService.GetCompanyMenu();

			return View(items);
		}
	}
}

KidscotchWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kid hop Scotch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kid hop Scotch</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home"></i> Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark font-text dropdown-toggle" href="#" id="drop1"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-tasks"></i>Operations</a>
                                <div class="dropdown-menu" aria-labelledby="drop1">
                                    <a class="dropdown-item" asp-area="" asp-controller="ShopCategories" asp-action="Index">Categories</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="ClothCompanies" asp-action="Index">Companies</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="ClothInfoes" asp-action="Index">Cloth Info</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark  font-text" asp-area="Identity" asp-page="/Account/RegisterAdmin"><i class="fa fa-user-plus"></i> Register Admin</a>
                            </li>
                        }
                        else
                        {
                            @await Component.InvokeAsync("CategoryMenu")
                            @await Component.InvokeAsync("CompanyMenu")
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MyCart"><i class="fa fa-shopping-cart"></i> Cart</a>
                            </li>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MyOrders"><i class="fa fa-tasks"></i> Orders</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Kid hop Scotch
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>